### PR TITLE
Test Harness Implementation

### PR DESCRIPTION
**Pull request by aarongraham9**
WIP on Test Harness Implementation.

Signed-off-by: Aaron Graham <aaron.graham@unb.ca>

### CODE REVIEW

**Comment by aarongraham9** [comment]
FYI @jeanlego. Still working on it. I'll update this PR as I go. Feel free to add your input here in the comments if you see anything you don't like. :)

**Comment by aarongraham9** [comment]
It's coming along. Nearly there I think. @jeanlego it should be close enough for you to start taking a look at it if you have the time. There are also a few bugs in the library that I may have discovered. I'll file issues later on today when I get the chance. :-)

**Comment by aarongraham9** [comment]
A small amount of cleanup.

**Comment by jeanlego** [comment]
Hey I think you can merge this and dev it on master as we're working on two separate things. Especially since there's nothing stable related to testing there may as well build it there I think, prevents us having to resolve merge conflict down the line 
Issues should be enough to track things.
Up to you!

**Comment by aarongraham9** [comment]
Ok good to merge!

**Review by jeanlego — APPROVED** [review]

**Pull request merged**
