### PR TITLE
Refactoring and Build System

### PR DESCRIPTION
**Pull request by aarongraham9**
Refactored code structure so the `librtlnumber` directory can be copied and pasted into VTR's `libs/` directory directly.

Necessary build system components from VTR project. Should be seamless when we go to migrate it back to VTR.

Commands:  `make distclean`,  `make clean` and `make -j`nproc --all | awk '{s=$1+1} END {print s}'` all` (GitHub.com's Markdown fucked the formatting on this command. Check the RAW to copy/paste it.) all work as before from the VTR .

To execute the test binary `rtl_number` built by the build system you can execute: 
`./build/libs/librtlnumber/rtl_number`

I'm still working to get the test binary to build/copy to inside the library directory `./libs/librtlnumber/rtl_number` like `./libs/libarchfpga/read_arch` does for `libarchfpga`.

Signed-off-by: Aaron Graham <aaron.graham@unb.ca>

### CODE REVIEW

**Comment by aarongraham9** [comment]
Hey @jeanlego! Let me know if you have any thoughts before I go ahead and merge this into `master`. :-)

**Comment by jeanlego** [comment]
Looks good to me! Any reason to include Odin stuff? I didn't dive into it.

**Comment by aarongraham9** [comment]
Yes. Super stripped down version of Odin. Pretty much just Odin's main.cpp and build system files. Makes it super easy for us to get the library linked into Odin when we get to that point (pretty much already done via this PR).

**Comment by aarongraham9** [comment]
Feel free to merge this whenever you're comfortable. :-)

**Comment by aarongraham9** [comment]
Fix so that the test binary to builds/copies to inside the library directory `./libs/librtlnumber/rtl_number`.

This should be good to merge now whenever you're happy with it @jeanlego.

**Comment by aarongraham9** [comment]
Now including the `rtl_int.h` header in the `Odin` test handle and calling out to the `arithmetic()` function.

Previous merge readiness statement from last comments still stands. :-)

**Pull request merged**
